# Audit policy syntax:
# A policy is defined in Yaml syntax. A policy is composed of rules. Each rule the following syntax:
# id: unique ID of rule. Can be used to reference the rule by other rules. Format: positive integer.
# name: meaningful rule name, presented to user on event match. Should be unique.
# documentation: optional, rule documentation string.
# namespace: optional, name of rules group. 'system' is reserved.
# status: true/false (default: true), indicates if matches should be reported
# combine-op: and/or (default: and), the logical operator to combine conditions values
# conditions: one or more logical conditions to match audit entries
#   a reference condition: has the logical value of another rule, whose id is the same as the ref-id. For example: {ref-id: 1}
#   a logical condition: matches an audit entry's field to the match-value using a match operator
#   field: audit entry field name:
#      principal
#      user-id
#      username
#      user-groups
#
#      impersonated-principal
#      impersonated-user-id
#      impersonated-username
#      impersonated-groups
#
#      access-type
#
#      caller-ip
#      caller-ip-asn
#      caller-ip-country
#
#      api-group
#      api-version
#      resource-type
#      resource-namespace
#      resource-name
#      subresource
#      subresource-exec-command
#      subresource-exec-container
#      subresource-exec-tty
#      subresource-exec-stdin
#      subresource-exec-stdout
#      subresource-logs-container
#      unusual-uri
#      verb
#
#      role
#      cluster-role
#
#      non-authorized
#      status
#      status-code
#      status-reason
#
#      original-user-agent
#      caller-supplied-user-agent
#
#      ua-command
#      ua-gcloud
#      ua-python
#      ua-term
#      ua-mozilla
#      ua-applewebkit
#      ua-chrome
#      ua-safari
#   match-op: =/!=/~/!~ (equals, non-equals, regex-match, non-regex-match
#   match-value: value used in match operation. Empty value with = match-op can be used to match event who doesn't have the field.
#
# Example:
#- id: 1
#  name: pod execution in production namespaces
#  description: execution of pods in namespaces whose name contains 'production'
#  conditions:
#   - {ref-id: 2}
#   - {field: resource-namespace, match-op: ~, match-value: production}
#- id: 2
#  name: pod execution rule
#  status: false
#  combine-op: and
#  conditions:
#   - {field: verb, match-op: =, match-value: create}
#   - {field: resource-type, match-op: =, match-value: pods}
#   - {field: subresource, match-op: =, match-value: exec}



- id: 100001
  name: "ops - pod creation"
  documentation: rule added by ops team
  status: false  
  conditions:
    - {field: verb, match-op: =, match-value: create}
    - {field: resource-type, match-op: =, match-value: pods}
    - {field: subresource, match-op: =, match-value: ''}
- id: 100002
  name: "sec - pod execution"
  documentation: rule added by security team for compliance requirement
  status: false   
  conditions:
    - {field: resource-type, match-op: =, match-value: pods}
    - {field: subresource, match-op: =, match-value: exec}
- id: 100003
  name: ops - namespace created
  status: false
  combine-op: and
  conditions:
    - {field: verb, match-op: =, match-value: create}
    - {field: resource-type, match-op: =, match-value: namespace}
- id: 100004
  name: ops - resource created in the default namespace
  status: false
  combine-op: and
  conditions:
    - {field: verb, match-op: =, match-value: create}
    - {field: resource-namespace, match-op: =, match-value: default}

#
# Enforcement Example
#
# - id: 200001
#   name: enforce - deny exec into kube-system 
#   status: true
#   combine-op: and
#   conditions:
#     - {field: resource-type, match-op: =, match-value: pods}
#     - {field: subresource, match-op: =, match-value: exec}
#     - {field: resource-namespace, match-op: =, match-value: kube-system}
#   enforcement: {} # Use {} to specify an indefinite enforcement rule
#     #time-limit: 0 # Expressed in miliseconds. Must be a positive integer
#     #count-limit: 5 # Limit the number of hits on this rule. Must be a positive integer
