apiVersion: v1
kind: ConfigMap
metadata:
  name: kaudit-policy-{{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: kaudit
    app-name: kaudit-{{ .Values.clusterName }}
data:
  audit-policy: |
{{ .Files.Get .Values.kauditPolicyFile  | indent 4 -}}


